### PR TITLE
Adding django-filer plugin and creating protocols page

### PR DESCRIPTION
**Pull request by carze**
Takes care of creating a protocols page through the use of the django-filer plugin.

### CODE REVIEW

**Comment by ljmciver** [comment]
Hi Cesar,

It looks like there is a typo in "jdrf/pages/templates/index.html". There is an extra "a". Also for prod we want nginx to host media files. Could you add media to nginx config and remove from jdrf/urls.py ?

Thanks!
Lauren

**Comment by carze** [comment]
Think things should be all set now to serve from nginx.

**Comment by ljmciver** [comment]
Hi Cesar - It looks like the settings and ngix config are not quite in sync. I think we need to add "media/" to the config. 

Thanks,
Lauren

**Comment by ljmciver** [comment]
Hi Cesar - Ignore the last message; I was reading it wrong. Trying to do too many things at once! It looks like we are all set.

Thanks,
Lauren

**Pull request merged**
